### ISSUE TITLE
Search Not Restricted to US or Seattle Area

### ISSUE THREAD

**Issue by marishuman** [Local-Connectivity-Lab/ccn-coverage-vis#27]
# Description 
When a user searches for an address, the autocomplete includes addresses not within the US. 

# Screenshots
![image](https://user-images.githubusercontent.com/82297766/209891352-4daaed50-0eb8-43e1-84a6-6d1ebf7819ad.png)

**Comment by marishuman** [comment]
Look into the documentation for the provider

**Comment by mmt456** [comment]
created new branch "issue27" from main. Then added new "countrycodes" parameter to OpenStreetMapProvider to limit search to USA. Works, not deployed yet.
