### ISSUE TITLE
Cannot Reopen Average Signal Strength Pop-Up

### ISSUE THREAD

**Issue by marishuman** [Local-Connectivity-Lab/ccn-coverage-vis#28]
# Description
Once you "hide" the Average Signal Strength pop-up in the right corner, you cannot make it reappear.

# Screenshots
![image](https://user-images.githubusercontent.com/82297766/211404911-2ee584dc-16bc-4af1-adf0-dfd6a7bd6df3.png)
![image](https://user-images.githubusercontent.com/82297766/211404969-d1fcc0b6-dea1-43a8-b752-b4b705312093.png)

**Comment by mmt456** [comment]
new visibility icon button code has been merged, will be deployed now.

**Comment by philion** [comment]
Has been deployed. Closing.
