### ISSUE TITLE
Webscraper: Stand up a FastAPI server that accepts a get request

### ISSUE THREAD

**Issue by philion** [Local-Connectivity-Lab/ccn-coverage-vis#38]
Implement a simple HTTP GET method at "/" to accept an address string as input, and invoke the scraper logic (a different  issue), and return the JSON response in the API response.

Document how to start the webscraper service in the README.

**Comment by Aaron8727** [comment]
I fixed the HTTP GET issue so you can now run the API with the following URL: "http://127.0.0.1:8000/?state=va&cityname=arlington&primary=3109&street_number=9th&st=St&post_direction=N&zip_5=22201"

**Comment by philion** [comment]
Great! Yeah, we need to be able to parse the data out of the original URL and apply it to the call to allconnect.

Let's leave this issue open until we've got the server running with expected behavior.

**Comment by philion** [comment]
Also, @Aaron8727: Assign this ticket to yourself (see top right **Assignees**) to track working on which features.

**Comment by philion** [comment]
This is complete. the code is at https://github.com/Local-Connectivity-Lab/ccn-coverage-scraper
